name: ash-ecrf-platform

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  rector-ci:
    runs-on: ubuntu-latest
    # run only on commits on main repository, not on forks
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - run: composer install --no-progress --ansi --prefer-dist --no-interaction --no-suggest

      ## First run Rector without --dry-run, it would stop the process with exit 1 here
      - run: vendor/bin/rector process --ansi

      - name: Check for Rector modified files
        id: rector-git-check
        run: echo ::set-output name=modified::$(if git diff --exit-code --no-patch; then echo "false"; else echo "true"; fi)

      - name: Git config
        if: steps.rector-git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'rector-bot'
          git config --global user.email 'devops+bot@prometheusresearch.com'
          echo name=COMMIT_MESSAGE::$(git log -1 --pretty=format:"%s") >> "${GITHUB_ENV}"

      - name: Commit Rector changes
        if: steps.rector-git-check.outputs.modified == 'true'
        run: git commit -am "[rector] ${COMMIT_MESSAGE}"

      - name: Push changes
        if: steps.rector-git-check.outputs.modified == 'true'
        run: git push

      ## Run tests
      - name: Execute tests
        run: ./vendor/bin/pest
